### PR TITLE
Include Android Oreo 8.1 ASOP Emoji

### PR DESCRIPTION
**Pull request by jul-sh**
Would love this, to make my phone feels like more of a Pixel. I'm not entirely sure if I updated all necessary files, as I'm new to Android Dev

### CODE REVIEW

**Comment by ohayoubaka** [comment]
Have you verified if the text isn't all spaced out when you apply the Oreo emojis?

**Comment by laurajuliette** [comment]
I haven't, no. When I'll be home I'll see if I come build an apk to test, never done Android development so far

**Comment by MihailMihov** [comment]
Also your <filename> tag in xml/ was broken, I made a commit to fix it make
sure that you build with that commit.

**Comment by laurajuliette** [comment]
Awesome, thank you. Will do that

**Pull request closed without merging**
